<<<<<<< HEAD
# Site settings
title: Contemporary Romance Author Ava Blake
email: authorcora@gmail.com
description: Homepage of Contemporary Romance writer Ava Blake
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.avablake.com" # the base hostname & protocol for your site
twitter_username: #jekyllrb
github_username:  #jekyll

# Build settings
markdown: redcarpet
#highlighter: rouge
=======
name: Ava Blake
markdown: redcarpet
pygments: true
encoding: UTF-8
>>>>>>> origin/master
